# project: dev-day-appengine

module: default
version: 1
runtime: python27
api_version: 1
threadsafe: yes

skip_files:
- .*\.sh

handlers:
- url: /static
  static_dir: static

- url: /
  static_files: static/index.html
  upload: static/index\.html

- url: .*  # This regex directs all routes to main.app
  script: main.app
